[package]
name = "mdbook-snippets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.7"
mdbook = "0.4.35"
serde_json = "1.0.108"

[workspace]
