variables:
  CI_DISPOSABLE_ENVIRONMENT: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

.base:
  image: xenoky/lwk-builder@sha256:cf903e51edabc1a203919ee1911d0f3fde93461db5208b10996cc1e1644c8d9b
  tags:
    - cloud
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - stuck_or_timeout_failure  
  services:
    - docker:20.10.12-dind

wasm:
  extends: .base
  variables:
    RUSTFLAGS: "--cfg=web_sys_unstable_apis"
    CARGO_PROFILE_RELEASE_OPT_LEVEL: z
    WASM_BINDGEN_TEST_TIMEOUT: 60
    JAVA_OPTS: "-Dwebdriver.chrome.whitelistedIps="
    CHROME_FLAGS: "--no-sandbox --headless --disable-dev-shm-usage --disable-gpu --disable-software-rasterizer --no-zygote"
  script:
    - cp ./context/env.sh / && cd / && . ./env.sh && cd -
    - cargo check --target wasm32-unknown-unknown -p lwk_common -p lwk_rpc_model -p lwk_containers -p lwk_hwi
    - cargo check --target wasm32-unknown-unknown -p lwk_wollet --no-default-features --features esplora,serial
    - cargo check --target wasm32-unknown-unknown -p lwk_signer --no-default-features
    - cargo check --target wasm32-unknown-unknown -p lwk_jade --no-default-features --features asyncr --features serial
    - cargo check --target wasm32-unknown-unknown -p lwk_ledger --no-default-features
    - (cd lwk_wasm && wasm-pack test --chrome --headless --features serial)
    - (cd lwk_wasm && wasm-pack build --features serial)
  artifacts:
    paths:
      - lwk_wasm/pkg
