variables:
  CI_DISPOSABLE_ENVIRONMENT: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

.base:
  image: xenoky/lwk-builder@sha256:b3ed5a58a179e228cc25c632ce28aaab641df247fef9c649064a3eff44773b87
  tags:
    - cloud
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - stuck_or_timeout_failure  
  services:
    - docker:20.10.12-dind

wasm:
  extends: .base
  variables:
    WASM_BINDGEN_TEST_RUNNER_ARGS: "--no-sandbox --disable-dev-shm-usage --remote-debugging-address=127.0.0.1 --disable-ipv6"
    WASM_BINDGEN_TEST_TIMEOUT: 60
    RUSTFLAGS: "--cfg=web_sys_unstable_apis"
  script:
    - (cd lwk_wasm &&  wasm-pack test --chrome --headless --features serial)

