[package]
name = "lwk-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
lwk_jade = { path = "../lwk_jade", default-features = false, features = ["fuzzing"] }
lwk_payment_instructions = { path = "../lwk_payment_instructions" }
lwk_wollet = { path = "../lwk_wollet", default-features = false }
serde_cbor = "0.11.2"

[patch.crates-io]
lwk_common = { path = "../lwk_common" }
lwk_registry = { path = "../lwk_registry" }

[workspace]
members = ["."]

[[bin]]
name = "update_deserialize"
path = "fuzz_targets/update_deserialize.rs"
test = false
doc = false
bench = false

[[bin]]
name = "jade_response"
path = "fuzz_targets/jade_response.rs"
test = false
doc = false
bench = false

[[bin]]
name = "payment_instruction"
path = "fuzz_targets/payment_instruction.rs"
test = false
doc = false
bench = false
