use crate::{Error, Network, Pset, Transaction, Txid, Update, Wollet, WolletDescriptor};
use lwk_wollet::{age, clients::asyncr};
use wasm_bindgen::prelude::*;
#[cfg(all(feature = "browser", target_arch = "wasm32"))]
use wasm_bindgen::JsCast;
#[cfg(all(feature = "browser", target_arch = "wasm32"))]
use wasm_bindgen_futures::js_sys::{Error as JsError, Function, JSON};

/// Response from the last_used_index endpoint
///
/// Returns the highest derivation index that has been used (has transaction history)
/// for both external and internal chains. This is useful for quickly determining
/// the next unused address without downloading full transaction history.
#[wasm_bindgen]
pub struct LastUsedIndexResponse {
    inner: asyncr::LastUsedIndexResponse,
}

#[wasm_bindgen]
impl LastUsedIndexResponse {
    /// Last used index on the external (receive) chain, or undefined if no addresses have been used.
    #[wasm_bindgen(getter)]
    pub fn external(&self) -> Option<u32> {
        self.inner.external
    }

    /// Last used index on the internal (change) chain, or undefined if no addresses have been used.
    #[wasm_bindgen(getter)]
    pub fn internal(&self) -> Option<u32> {
        self.inner.internal
    }

    /// Current blockchain tip hash for reference.
    #[wasm_bindgen(getter)]
    pub fn tip(&self) -> Option<String> {
        self.inner.tip.map(|t| t.to_string())
    }
}

impl From<asyncr::LastUsedIndexResponse> for LastUsedIndexResponse {
    fn from(inner: asyncr::LastUsedIndexResponse) -> Self {
        Self { inner }
    }
}

/// A blockchain backend implementation based on the
/// [esplora HTTP API](https://github.com/blockstream/esplora/blob/master/API.md).
/// But can also use the [waterfalls](https://github.com/RCasatta/waterfalls)
/// endpoint to speed up the scan if supported by the server.
#[wasm_bindgen]
pub struct EsploraClient {
    inner: asyncr::EsploraClient,
    /// The builder used to create the client, stored for recreation
    builder: asyncr::EsploraClientBuilder,
}

/// A blockchain backend implementation based on the
/// [Waterfalls HTTP API](https://github.com/RCasatta/waterfalls).
#[wasm_bindgen]
pub struct WaterfallsClient {
    inner: asyncr::WaterfallsClient,
}

/// A browser EventSource-backed Waterfalls descriptor subscription stream.
#[cfg(all(feature = "browser", target_arch = "wasm32"))]
#[wasm_bindgen]
pub struct WaterfallsSubscription {
    source: web_sys::EventSource,
    on_update: Closure<dyn FnMut(web_sys::MessageEvent)>,
    on_error: Option<Closure<dyn FnMut(web_sys::Event)>>,
}

/// A builder for constructing [`WaterfallsClient`] instances.
#[wasm_bindgen]
pub struct WaterfallsClientBuilder {
    inner: asyncr::WaterfallsClientBuilder,
}

impl From<asyncr::WaterfallsClientBuilder> for WaterfallsClientBuilder {
    fn from(value: asyncr::WaterfallsClientBuilder) -> Self {
        Self { inner: value }
    }
}

impl AsRef<asyncr::EsploraClient> for EsploraClient {
    fn as_ref(&self) -> &asyncr::EsploraClient {
        &self.inner
    }
}

impl EsploraClient {
    /// Create a new async client with the same connection parameters
    pub(crate) fn clone_async_client(&self) -> Result<asyncr::EsploraClient, crate::Error> {
        self.builder
            .clone()
            .build()
            .map_err(|e| Error::Generic(e.to_string()))
    }
}

#[wasm_bindgen]
impl WaterfallsClientBuilder {
    /// Create a builder for a Waterfalls client.
    #[wasm_bindgen(constructor)]
    pub fn new(network: &Network, url: &str) -> Self {
        asyncr::WaterfallsClientBuilder::new(url, network.into()).into()
    }

    /// Set the concurrency level for requests, default is 1.
    ///
    /// Concurrency can't be 0; if 0 is passed, 1 will be used.
    pub fn concurrency(self, concurrency: usize) -> Self {
        self.inner.concurrency(concurrency).into()
    }

    /// Whether the client is "utxo only".
    ///
    /// **Experimental**: This API may change without notice.
    #[wasm_bindgen(js_name = utxoOnly)]
    pub fn utxo_only(self, utxo_only: bool) -> Self {
        self.inner.utxo_only(utxo_only).into()
    }

    /// Build the Waterfalls client from this builder.
    pub fn build(self) -> Result<WaterfallsClient, Error> {
        Ok(WaterfallsClient {
            inner: self
                .inner
                .build()
                .map_err(|e| Error::Generic(e.to_string()))?,
        })
    }
}

#[wasm_bindgen]
impl WaterfallsClient {
    /// Creates a Waterfalls client with default options. Use the WaterfallsClientBuilder for more setup options.
    #[wasm_bindgen(constructor)]
    pub fn new(network: &Network, url: &str) -> Self {
        Self {
            inner: asyncr::WaterfallsClient::new(network.into(), url),
        }
    }

    /// Scan the blockchain for the scripts generated by a watch-only wallet.
    #[wasm_bindgen(js_name = fullScan)]
    pub async fn full_scan(&mut self, wollet: &Wollet) -> Result<Option<Update>, Error> {
        let update: Option<lwk_wollet::Update> = self.inner.full_scan(wollet.as_ref()).await?;
        Ok(update.map(Into::into))
    }

    /// Scan the blockchain for the scripts generated by a watch-only wallet up to a specified derivation index.
    #[wasm_bindgen(js_name = fullScanToIndex)]
    pub async fn full_scan_to_index(
        &mut self,
        wollet: &Wollet,
        index: u32,
    ) -> Result<Option<Update>, Error> {
        let update: Option<lwk_wollet::Update> = self
            .inner
            .full_scan_to_index(wollet.as_ref(), index)
            .await?;
        Ok(update.map(Into::into))
    }

    /// Broadcast a transaction to the network so that a miner can include it in a block.
    #[wasm_bindgen(js_name = broadcastTx)]
    pub async fn broadcast_tx(&mut self, tx: &Transaction) -> Result<Txid, Error> {
        let txid = self.inner.broadcast(tx.as_ref()).await?;
        Ok(txid.into())
    }

    /// Broadcast a PSET by extracting the transaction from the PSET and broadcasting it.
    pub async fn broadcast(&mut self, pset: &Pset) -> Result<Txid, Error> {
        let tx = pset.extract_tx()?;
        self.broadcast_tx(&tx).await
    }

    /// Set the Waterfalls server recipient key.
    #[wasm_bindgen(js_name = setWaterfallsServerRecipient)]
    pub async fn set_waterfalls_server_recipient(&mut self, recipient: &str) -> Result<(), Error> {
        let recipient: age::x25519::Recipient = recipient
            .parse()
            .map_err(|e: &str| Error::Generic(e.to_string()))?;
        self.inner.set_waterfalls_server_recipient(recipient);
        Ok(())
    }

    /// Return the descriptor string to use with Waterfalls descriptor endpoints.
    #[wasm_bindgen(js_name = waterfallsDescriptor)]
    pub async fn waterfalls_descriptor(
        &mut self,
        descriptor: &WolletDescriptor,
    ) -> Result<String, Error> {
        Ok(self
            .inner
            .waterfalls_descriptor(descriptor.as_ref())
            .await?)
    }

    /// Return the Waterfalls descriptor subscription URL for browser EventSource clients.
    #[wasm_bindgen(js_name = waterfallsSubscribeUrl)]
    pub async fn waterfalls_subscribe_url(
        &mut self,
        descriptor: &WolletDescriptor,
    ) -> Result<String, Error> {
        Ok(self
            .inner
            .waterfalls_subscribe_url(descriptor.as_ref())
            .await?)
    }

    /// Subscribe to Waterfalls descriptor updates using browser EventSource.
    ///
    /// `onChanged` is called as `onChanged(kind, rawData)`, where `kind` is
    /// `tip`, `mempool`, `block`, or `reorg`, and `rawData` is the raw SSE data
    /// string. Browser EventSource cannot set custom authentication headers.
    #[cfg(all(feature = "browser", target_arch = "wasm32"))]
    pub async fn subscribe(
        &mut self,
        descriptor: &WolletDescriptor,
        on_changed: Function,
        on_error: Option<Function>,
    ) -> Result<WaterfallsSubscription, Error> {
        let url = self
            .inner
            .waterfalls_subscribe_url(descriptor.as_ref())
            .await?;
        let source = web_sys::EventSource::new(&url).map_err(Error::JsVal)?;

        let on_error_for_update = on_error.clone();
        let on_update = Closure::wrap(Box::new(move |event: web_sys::MessageEvent| {
            let Some(data) = event.data().as_string() else {
                if let Some(on_error) = &on_error_for_update {
                    let error = JsError::new("Waterfalls SSE update event data is not a string");
                    let _ = on_error.call1(&JsValue::NULL, error.as_ref());
                }
                return;
            };

            let kind = JSON::parse(&data).ok().and_then(|value| {
                js_sys_reflect_get(&value, "type")
                    .ok()
                    .and_then(|kind| kind.as_string())
            });

            let Some(kind) = kind else {
                if let Some(on_error) = &on_error_for_update {
                    let error = JsError::new("Invalid Waterfalls SSE update event");
                    let _ = on_error.call1(&JsValue::NULL, error.as_ref());
                }
                return;
            };

            let _ = on_changed.call2(&JsValue::NULL, &JsValue::from(kind), &JsValue::from(data));
        }) as Box<dyn FnMut(_)>);
        source
            .add_event_listener_with_callback("update", on_update.as_ref().unchecked_ref())
            .map_err(Error::JsVal)?;

        let on_error = if let Some(on_error) = on_error {
            let on_error = Closure::wrap(Box::new(move |event: web_sys::Event| {
                let _ = on_error.call1(&JsValue::NULL, &event.into());
            }) as Box<dyn FnMut(_)>);
            source.set_onerror(Some(on_error.as_ref().unchecked_ref()));
            Some(on_error)
        } else {
            None
        };

        Ok(WaterfallsSubscription {
            source,
            on_update,
            on_error,
        })
    }

    /// Query the last used derivation index for a wallet's descriptor from the Waterfalls server.
    #[wasm_bindgen(js_name = lastUsedIndex)]
    pub async fn last_used_index(
        &mut self,
        descriptor: &WolletDescriptor,
    ) -> Result<LastUsedIndexResponse, Error> {
        let result = self.inner.last_used_index(descriptor.as_ref()).await?;
        Ok(result.into())
    }
}

#[cfg(all(feature = "browser", target_arch = "wasm32"))]
fn js_sys_reflect_get(value: &JsValue, field: &str) -> Result<JsValue, JsValue> {
    wasm_bindgen_futures::js_sys::Reflect::get(value, &JsValue::from(field))
}

#[cfg(all(feature = "browser", target_arch = "wasm32"))]
#[wasm_bindgen]
impl WaterfallsSubscription {
    /// Close the underlying browser EventSource stream.
    pub fn close(&self) {
        let _ = self
            .source
            .remove_event_listener_with_callback("update", self.on_update.as_ref().unchecked_ref());
        self.source.set_onerror(None);
        self.source.close();
        let _ = &self.on_error;
    }
}

#[cfg(all(feature = "browser", target_arch = "wasm32"))]
impl Drop for WaterfallsSubscription {
    fn drop(&mut self) {
        self.close();
    }
}

#[wasm_bindgen]
impl EsploraClient {
    /// Creates an Esplora client with the given options
    #[wasm_bindgen(constructor)]
    pub fn new(
        network: &Network,
        url: &str,
        waterfalls: bool,
        concurrency: usize,
        utxo_only: bool,
    ) -> Result<Self, Error> {
        #[allow(deprecated)]
        let builder = asyncr::EsploraClientBuilder::new(url, network.into())
            .waterfalls(waterfalls)
            .concurrency(concurrency)
            .utxo_only(utxo_only);
        let inner = builder
            .clone()
            .build()
            .map_err(|e| Error::Generic(e.to_string()))?;
        Ok(Self { inner, builder })
    }

    /// Scan the blockchain for the scripts generated by a watch-only wallet
    ///
    /// This method scans both external and internal address chains, stopping after finding
    /// 20 consecutive unused addresses (the gap limit) as recommended by
    /// [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit).
    ///
    /// Returns `Some(Update)` if any changes were found during scanning, or `None` if no changes
    /// were detected.
    ///
    /// To scan beyond the gap limit use `full_scan_to_index()` instead.
    #[wasm_bindgen(js_name = fullScan)]
    pub async fn full_scan(&mut self, wollet: &Wollet) -> Result<Option<Update>, Error> {
        let update: Option<lwk_wollet::Update> = self.inner.full_scan(wollet.as_ref()).await?;
        Ok(update.map(Into::into))
    }

    /// Scan the blockchain for the scripts generated by a watch-only wallet up to a specified derivation index
    ///
    /// While `full_scan()` stops after finding 20 consecutive unused addresses (the gap limit),
    /// this method will scan at least up to the given derivation index. This is useful to prevent
    /// missing funds in cases where outputs exist beyond the gap limit.
    ///
    /// Will scan both external and internal address chains up to the given index for maximum safety,
    /// even though internal addresses may not need such deep scanning.
    ///
    /// If transactions are found beyond the gap limit during this scan, subsequent calls to
    /// `full_scan()` will automatically scan up to the highest used index, preventing any
    /// previously-found transactions from being missed.
    ///
    /// See `full_scan_to_index()` for a blocking version of this method.
    #[wasm_bindgen(js_name = fullScanToIndex)]
    pub async fn full_scan_to_index(
        &mut self,
        wollet: &Wollet,
        index: u32,
    ) -> Result<Option<Update>, Error> {
        let update: Option<lwk_wollet::Update> = self
            .inner
            .full_scan_to_index(wollet.as_ref(), index)
            .await?;
        Ok(update.map(Into::into))
    }

    /// Broadcast a transaction to the network so that a miner can include it in a block.
    #[wasm_bindgen(js_name = broadcastTx)]
    pub async fn broadcast_tx(&mut self, tx: &Transaction) -> Result<Txid, Error> {
        let txid = self.inner.broadcast(tx.as_ref()).await?;
        Ok(txid.into())
    }

    /// Broadcast a PSET by extracting the transaction from the PSET and broadcasting it.
    pub async fn broadcast(&mut self, pset: &Pset) -> Result<Txid, Error> {
        let tx = pset.extract_tx()?;
        self.broadcast_tx(&tx).await
    }

    /// Set the waterfalls server recipient key. This is used to encrypt the descriptor when calling the waterfalls endpoint.
    #[wasm_bindgen(js_name = setWaterfallsServerRecipient)]
    #[allow(deprecated)]
    pub async fn set_waterfalls_server_recipient(&mut self, recipient: &str) -> Result<(), Error> {
        let recipient: age::x25519::Recipient = recipient
            .parse()
            .map_err(|e: &str| Error::Generic(e.to_string()))?;
        self.inner.set_waterfalls_server_recipient(recipient);
        Ok(())
    }

    /// Return the descriptor string to use with Waterfalls descriptor endpoints.
    ///
    /// This is a temporary API exposed to let callers use Waterfalls subscription
    /// endpoints directly. It may be removed once subscription support is
    /// implemented in LWK.
    ///
    /// The returned descriptor has key origin information stripped and is encrypted
    /// for the Waterfalls server recipient unless descriptor encryption has been
    /// explicitly disabled on this client.
    #[wasm_bindgen(js_name = waterfallsDescriptor)]
    #[allow(deprecated)]
    pub async fn waterfalls_descriptor(
        &mut self,
        descriptor: &WolletDescriptor,
    ) -> Result<String, Error> {
        Ok(self
            .inner
            .waterfalls_descriptor(descriptor.as_ref())
            .await?)
    }

    /// Query the last used derivation index for a wallet's descriptor from the waterfalls server.
    ///
    /// This method queries the waterfalls `/v1/last_used_index` endpoint to get the last used
    /// derivation index for both external and internal chains of the wallet's descriptor.
    ///
    /// Returns `LastUsedIndexResponse` containing the last used indexes and the tip block hash.
    ///
    /// # Errors
    ///
    /// Returns an error if this client was not configured with waterfalls support,
    /// if the descriptor does not contain a wildcard,
    /// or if the descriptor uses ELIP151 blinding.
    #[wasm_bindgen(js_name = lastUsedIndex)]
    pub async fn last_used_index(
        &mut self,
        descriptor: &WolletDescriptor,
    ) -> Result<LastUsedIndexResponse, Error> {
        let result = self.inner.last_used_index(descriptor.as_ref()).await?;
        Ok(result.into())
    }
}

#[cfg(all(test, target_arch = "wasm32"))]
mod tests {

    use wasm_bindgen_test::*;

    wasm_bindgen_test_configure!(run_in_browser);

    #[wasm_bindgen_test]
    async fn test_sleep() {
        assert!(lwk_wollet::clients::asyncr::async_sleep(1).await.is_ok());
    }
}
