# From https://github.com/breez/breez-sdk-liquid-docs

[package]
name = "mdbook-snippets"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.7"
mdbook = "0.4.35"
serde_json = "1.0.108"

[workspace]
