-- Migrations are copied from https://github.com/BlockstreamResearch/simplicity-lending/tree/main/crates/indexer/migrations
CREATE TYPE vault_type AS ENUM ('lender', 'protocol_fee');

CREATE TABLE offer_vaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
    vault_type vault_type NOT NULL,

    txid BYTEA NOT NULL,
    vout INTEGER NOT NULL,
    amount BIGINT NOT NULL,
    already_supplied BIGINT NOT NULL,
    is_finalized BOOLEAN NOT NULL DEFAULT false,

    created_at_height BIGINT NOT NULL,
    updated_at_height BIGINT NOT NULL,

    spent_txid BYTEA,
    spent_at_height BIGINT,

    UNIQUE (txid, vout)
);

-- At most one active vault of each type per offer at any given time.
CREATE UNIQUE INDEX idx_offer_vaults_active_per_type
ON offer_vaults (offer_id, vault_type)
WHERE spent_txid IS NULL;

CREATE TABLE offer_vault_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
    vault_type vault_type NOT NULL,
    txid BYTEA NOT NULL,
    height BIGINT NOT NULL,
    is_full BOOLEAN NOT NULL,
    amount_withdrawn BIGINT NOT NULL,
    vault_amount_before BIGINT NOT NULL,
    vault_amount_after BIGINT NOT NULL,
    UNIQUE (txid, vault_type)
);

CREATE INDEX idx_offer_vault_withdrawals_offer_id_height
ON offer_vault_withdrawals (offer_id, height DESC);
