-- Migrations are copied from https://github.com/BlockstreamResearch/simplicity-lending/tree/main/crates/indexer/migrations
ALTER TABLE offers
    ADD COLUMN current_debt BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN collateral_remaining BIGINT NOT NULL DEFAULT 0;

CREATE TABLE offer_repayments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
    txid BYTEA NOT NULL,
    height BIGINT NOT NULL,
    amount_repaid BIGINT NOT NULL,
    collateral_unlocked BIGINT NOT NULL,
    debt_before BIGINT NOT NULL,
    debt_after BIGINT NOT NULL,
    collateral_before BIGINT NOT NULL,
    collateral_after BIGINT NOT NULL,
    is_full BOOLEAN NOT NULL,
    UNIQUE (txid)
);

CREATE INDEX idx_offer_repayments_offer_id_height
    ON offer_repayments (offer_id, height DESC);
