[book]
title = "LWK Documentation"
author = "LWK Contributors"

[output.html]
git-repository-url = "https://github.com/blockstream/lwk"
edit-url-template = "https://github.com/blockstream/lwk/edit/master/docs/src/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
