use std::collections::{HashMap, HashSet};

use age::x25519::Recipient;
use elements::{BlockHash, Script, Txid};

use crate::{
    cache::Height,
    clients::{
        waterfalls::waterfalls_subscribe_url, Capability, Data, History, WaterfallsClientBuilder,
    },
    wollet::WolletState,
    Error, Network, Update, Wollet, WolletDescriptor,
};

use super::{EsploraClient, LastUsedIndexResponse};

#[derive(Debug)]
/// A blockchain backend implementation based on the
/// [Waterfalls HTTP API](https://github.com/RCasatta/waterfalls).
///
/// Waterfalls is Esplora-compatible for common chain operations and adds
/// descriptor-based wallet scan endpoints.
pub struct WaterfallsClient {
    inner: EsploraClient,
}

impl WaterfallsClient {
    /// Creates a new Waterfalls client with default options using the given `url` as endpoint.
    ///
    /// To specify different options use the [`WaterfallsClientBuilder`].
    pub fn new(network: Network, url: &str) -> Self {
        WaterfallsClientBuilder::new(url, network)
            .build()
            .expect("cannot fail with this configuration")
    }

    /// Async version of [`crate::blocking::BlockchainBackend::tip()`].
    pub async fn tip(&mut self) -> Result<elements::BlockHeader, crate::Error> {
        self.inner.tip().await
    }

    /// Async version of [`crate::blocking::BlockchainBackend::broadcast()`].
    pub async fn broadcast(
        &self,
        tx: &elements::Transaction,
    ) -> Result<elements::Txid, crate::Error> {
        self.inner.broadcast(tx).await
    }

    /// Fetch a transaction.
    pub async fn get_transaction(&self, txid: Txid) -> Result<elements::Transaction, Error> {
        self.inner.get_transaction(txid).await
    }

    /// Fetch concurrently a list of transactions.
    pub async fn get_transactions(
        &self,
        txids: &[Txid],
    ) -> Result<Vec<elements::Transaction>, Error> {
        self.inner.get_transactions(txids).await
    }

    /// Fetch concurrently a list of block headers.
    ///
    /// Optionally pass known blockhash to avoid some network roundtrips if already known.
    pub async fn get_headers(
        &self,
        heights: &[Height],
        height_blockhash: &HashMap<Height, BlockHash>,
    ) -> Result<Vec<elements::BlockHeader>, Error> {
        self.inner.get_headers(heights, height_blockhash).await
    }

    /// Get the transactions involved in a list of scripts.
    pub async fn get_scripts_history(
        &self,
        scripts: &[&Script],
    ) -> Result<Vec<Vec<History>>, Error> {
        self.inner.get_scripts_history(scripts).await
    }

    /// Scan the blockchain for the scripts generated by a watch-only wallet.
    pub async fn full_scan(&mut self, wollet: &Wollet) -> Result<Option<Update>, Error> {
        self.inner.full_scan(wollet).await
    }

    /// Scan the blockchain for the scripts generated by a watch-only wallet up to a specified derivation index.
    pub async fn full_scan_to_index(
        &mut self,
        wollet: &Wollet,
        index: u32,
    ) -> Result<Option<Update>, Error> {
        self.inner.full_scan_to_index(wollet, index).await
    }

    pub(crate) async fn get_history_waterfalls<S: WolletState>(
        &mut self,
        descriptor: &WolletDescriptor,
        cache: &S,
        to_index: u32,
    ) -> Result<Data, Error> {
        self.inner
            .get_history_waterfalls(descriptor, cache, to_index)
            .await
    }

    /// Return the descriptor string to use with Waterfalls descriptor endpoints.
    ///
    /// The returned descriptor has key origin information stripped and is encrypted
    /// for the Waterfalls server recipient unless descriptor encryption has been
    /// explicitly disabled on this client.
    pub async fn waterfalls_descriptor(
        &mut self,
        descriptor: &WolletDescriptor,
    ) -> Result<String, Error> {
        #[allow(deprecated)]
        self.inner.waterfalls_descriptor(descriptor).await
    }

    /// Return the Waterfalls descriptor subscription URL for browser EventSource clients.
    ///
    /// The URL uses the same descriptor preparation as [`Self::waterfalls_descriptor`]:
    /// key origin information is stripped and the descriptor is encrypted unless
    /// descriptor encryption has been explicitly disabled on this client.
    pub async fn waterfalls_subscribe_url(
        &mut self,
        descriptor: &WolletDescriptor,
    ) -> Result<String, Error> {
        #[allow(deprecated)]
        let desc = self.inner.waterfalls_descriptor(descriptor).await?;
        Ok(waterfalls_subscribe_url(&self.inner.base_url, &desc))
    }

    /// Query the last used derivation index for a descriptor from the Waterfalls server.
    pub async fn last_used_index(
        &mut self,
        descriptor: &WolletDescriptor,
    ) -> Result<LastUsedIndexResponse, Error> {
        self.inner.last_used_index(descriptor).await
    }

    /// Avoid encrypting the descriptor when calling the Waterfalls endpoint.
    pub fn avoid_encryption(&mut self) {
        #[allow(deprecated)]
        self.inner.avoid_encryption();
    }

    /// Returns the Waterfalls server recipient key using a cached value or by asking the server its key.
    pub async fn waterfalls_server_recipient(&mut self) -> Result<Recipient, Error> {
        self.inner.waterfalls_server_recipient().await
    }

    /// Set the Waterfalls server recipient key.
    ///
    /// This is used to encrypt the descriptor when calling the Waterfalls endpoint.
    pub fn set_waterfalls_server_recipient(&mut self, recipient: Recipient) {
        #[allow(deprecated)]
        self.inner.set_waterfalls_server_recipient(recipient);
    }

    /// Return the number of network requests made by this client.
    pub fn requests(&self) -> usize {
        self.inner.requests()
    }

    /// Whether the client is configured to only fetch transactions with unspent outputs.
    pub fn utxo_only(&self) -> bool {
        self.inner.utxo_only
    }

    pub(crate) fn capabilities(&self) -> HashSet<Capability> {
        self.inner.capabilities()
    }

    /// Returns true if the wallet has any tx using the first gap limit addresses.
    pub async fn has_txs(
        &self,
        descriptor: &WolletDescriptor,
        gap_limit: Option<u32>,
    ) -> Result<bool, Error> {
        self.inner.has_txs(descriptor, gap_limit).await
    }
}

impl WaterfallsClientBuilder {
    /// Consume the builder and build a new [`WaterfallsClient`].
    pub fn build(self) -> Result<WaterfallsClient, Error> {
        let mut builder = self.inner;
        builder.waterfalls = true;
        Ok(WaterfallsClient {
            inner: builder.build()?,
        })
    }
}
